version: "3.8"
services:
  app:
    build: .
    container_name: task_manager_node_app
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/taskdb

  mongo:
    image: mongo:latest
    container_name: task_manager_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
