version: '3.8'

services:
  # MongoDB service
  # mongo:
  #   image: mongo:6.0
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network

  # Redis service
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Go API service
  # go-api:
  #   build:
  #     context: ./go-api
  #     dockerfile: Dockerfile-go
  #   container_name: go-api
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/taskdb
  #     - REDIS_URL=redis://redis:6379
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #     - redis
  #   networks:
  #     - app-network

  # Node.js API service
  # node-api:
  #   build:
  #     context: ./node-api
  #     dockerfile: Dockerfile-node
  #   container_name: node-api
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/taskdb
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - app-network

  # # React frontend service
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile-frontend
  #   container_name: frontend
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - go-api
  #     - node-api
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
